name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  sles-15:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - libImlib2-1
      - imlib2
    build_dependencies:
      - libImlib2-1
      - https://ftp.gwdg.de/pub/opensuse/distribution/openSUSE-stable/repo/oss/x86_64/imlib2-devel-1.4.10-1.28.x86_64.rpm
      - shared-mime-info
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres:13
before_install: contrib/packager.io/preinstall.sh
after_install: contrib/packager.io/postinstall.sh
